spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:8081/userapi
    username: userapi_app
    password: HelloThere
    driver-class-name: org.postgresql.Driver
    platform: postgres